### PR TITLE
fetchmetadata: Update to new API.

### LINKED ISSUE #300: fetchmetadata: switch to configs for exceptions
The fetchmetadata plugin dates back to when we didn't have configs.

This means that exceptions for the protection must currently be passed on construction instead of handler registration.

We should switch to the new mechanism.

### PR DESCRIPTION
**Pull request by empijei**
Fixes #300

### CODE REVIEW

File: safehttp/plugins/fetchmetadata/fetchmetadata.go [hunk 1]
```diff
@@ -138,37 +126,56 @@ func (p *Plugin) SetEnforce() {
...
+	return w.WriteError(safehttp.StatusForbidden)
 }
 
 // Commit is a no-op, required to satisfy the safehttp.Interceptor interface.
-func (p *Plugin) Commit(w safehttp.ResponseHeadersWriter, r *safehttp.IncomingRequest, resp safehttp.Response, _ safehttp.InterceptorConfig) {
+func (p *Interceptor) Commit(w safehttp.ResponseHeadersWriter, r *safehttp.IncomingRequest, resp safehttp.Response, _ safehttp.InterceptorConfig) {
+}
+
+// Disable is a configuration that disables Fetch Metadata protection and switches
+// it to report-only.
```
Comment (kele) [inline safehttp/plugins/fetchmetadata/fetchmetadata.go:172]:
```suggestion
// Disable disables Fetch Metadata protection and switches it to report-only.
```

**Review by kele — APPROVED** [review]
